// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhTdK6Wz4KWqMwap9CdT4baQ6YgbOgQo',
    appId: '1:565593815316:web:e4639d5c91403d690eea01',
    messagingSenderId: '565593815316',
    projectId: 'driver-please-1b5ee',
    authDomain: 'driver-please-1b5ee.firebaseapp.com',
    storageBucket: 'driver-please-1b5ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfut4-OzTkObrw340UXOOTC8z_vzni-9E',
    appId: '1:565593815316:android:0bdb61e18368477e0eea01',
    messagingSenderId: '565593815316',
    projectId: 'driver-please-1b5ee',
    storageBucket: 'driver-please-1b5ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhsRl8bTeh8sqlNuPhFm_9RW3wJqE4Ws',
    appId: '1:565593815316:ios:7452c5e86919d43a0eea01',
    messagingSenderId: '565593815316',
    projectId: 'driver-please-1b5ee',
    storageBucket: 'driver-please-1b5ee.appspot.com',
    iosBundleId: 'com.driverplease.app',
  );
}
